version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  target-branch: main
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: "org.mariadb.jdbc:mariadb-java-client" ## version 3.0.3 of the driver drops support for Aurora - https://www.pivotaltracker.com/n/projects/2482247/stories/183282618
    update-types: ["version-update:semver-major"]
  - dependency-name: "org.springframework.boot:*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ] # Do major/minor version bumps manually as it will almost certainly require major migration.
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
