#!/bin/bash

if [ $(jps | grep -c -E 'GradleMain|AppMain') -ne 0 ]; then
  echo "It looks like you have a development server running already."
  echo "Please stop it and then re-run this command."
  exit 1
fi

function stop_dev_server() {
  jps | grep GradleMain | awk '{print $1}' | xargs kill -9
}

git pull -r &&
./gradlew clean test 
if [ $? -ne 0 ]; then
  echo "Unit tests failed."
  exit 1
fi

gradle bootRun 2>&1 > /dev/null &
if [ $? -ne 0 ]; then
  echo "Dev server failed to start."
  exit 1
fi

echo "Waiting for server to start."
sleep 10

pushd ~/go/src/github.com/pivotal-cf/cred-hub-acceptance-tests
  if [ -e config.json ]; then
    echo "Found an existing config.json, moving to .old"
    mv config.json config.json.old
  fi
  ./target_local.sh && ./run_tests.sh
  if [ $? -ne 0 ]; then
    echo "Acceptance tests failed."
    stop_dev_server
    exit 1
  fi
popd

echo "Stopping dev server."
stop_dev_server

git push && echo "Success"
