package org.cloudfoundry.credhub.audit;

public enum OperationDeviceAction {
  GET,
  SET,
  GENERATE,
  REGENERATE,
  BULK_REGENERATE,
  DELETE,
  FIND,
  GET_PERMISSIONS,
  ADD_PERMISSIONS,
  PUT_PERMISSIONS,
  PATCH_PERMISSIONS,
  DELETE_PERMISSIONS,
  INTERPOLATE,
  INFO,
  VERSION,
  HEALTH,
  KEY_USAGE,
  GET_ALL_CERTIFICATES, REGENERATE_CERTIFICATE, GET_CERTIFICATE, UPDATE_TRANSITIONAL_VERSION
}
