ALTER TABLE VALUE_SECRET ADD COLUMN UUID BINARY(16);
ALTER TABLE PASSWORD_SECRET ADD COLUMN UUID BINARY(16);
ALTER TABLE CERTIFICATE_SECRET ADD COLUMN UUID BINARY(16);
ALTER TABLE SSH_SECRET ADD COLUMN UUID BINARY(16);
ALTER TABLE RSA_SECRET ADD COLUMN UUID BINARY(16);

ALTER TABLE VALUE_SECRET DROP CONSTRAINT FKOX93SY15F6PGBDR89KP05PNFQ;
ALTER TABLE PASSWORD_SECRET DROP CONSTRAINT FK31HQE03PKUGU8U5NG564KO2NV;
ALTER TABLE CERTIFICATE_SECRET DROP CONSTRAINT FK34BRQRQSRTKAF3GMTY1RJKYJD;
ALTER TABLE SSH_SECRET DROP CONSTRAINT SSH_SECRET_FKEY;
ALTER TABLE RSA_SECRET DROP CONSTRAINT RSA_SECRET_FKEY;

ALTER TABLE VALUE_SECRET DROP PRIMARY KEY;
ALTER TABLE PASSWORD_SECRET DROP PRIMARY KEY;
ALTER TABLE CERTIFICATE_SECRET DROP PRIMARY KEY;
ALTER TABLE SSH_SECRET DROP PRIMARY KEY;
ALTER TABLE RSA_SECRET DROP PRIMARY KEY;

ALTER TABLE VALUE_SECRET ADD FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) NOCHECK;
ALTER TABLE PASSWORD_SECRET ADD FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) NOCHECK;
ALTER TABLE CERTIFICATE_SECRET ADD FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) NOCHECK;
ALTER TABLE SSH_SECRET ADD FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) NOCHECK;
ALTER TABLE RSA_SECRET ADD FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) NOCHECK;

UPDATE value_secret
  SET value_secret.uuid = (
    SELECT named_secret.uuid
    FROM named_secret
    WHERE value_secret.id = named_secret.id
  );
UPDATE password_secret
  SET password_secret.uuid = (
    SELECT named_secret.uuid
    FROM named_secret
    WHERE password_secret.id = named_secret.id
  );
UPDATE certificate_secret
  SET certificate_secret.uuid = (
    SELECT named_secret.uuid
    FROM named_secret
    WHERE certificate_secret.id = named_secret.id
  );
UPDATE ssh_secret
  SET ssh_secret.uuid = (
    SELECT named_secret.uuid
    FROM named_secret
    WHERE ssh_secret.id = named_secret.id
  );
UPDATE rsa_secret
  SET rsa_secret.uuid = (
    SELECT named_secret.uuid
    FROM named_secret
    WHERE rsa_secret.id = named_secret.id
  );

ALTER TABLE VALUE_SECRET ALTER COLUMN UUID BINARY(16) NOT NULL;
ALTER TABLE PASSWORD_SECRET ALTER COLUMN UUID BINARY(16) NOT NULL;
ALTER TABLE CERTIFICATE_SECRET ALTER COLUMN UUID BINARY(16) NOT NULL;
ALTER TABLE SSH_SECRET ALTER COLUMN UUID BINARY(16) NOT NULL;
ALTER TABLE RSA_SECRET ALTER COLUMN UUID BINARY(16) NOT NULL;

ALTER TABLE VALUE_SECRET ADD PRIMARY KEY(UUID);
ALTER TABLE PASSWORD_SECRET ADD PRIMARY KEY(UUID);
ALTER TABLE CERTIFICATE_SECRET ADD PRIMARY KEY(UUID);
ALTER TABLE SSH_SECRET ADD PRIMARY KEY(UUID);
ALTER TABLE RSA_SECRET ADD PRIMARY KEY(UUID);

ALTER TABLE VALUE_SECRET DROP COLUMN IF EXISTS ID;
ALTER TABLE PASSWORD_SECRET DROP COLUMN IF EXISTS ID;
ALTER TABLE CERTIFICATE_SECRET DROP COLUMN IF EXISTS ID;
ALTER TABLE SSH_SECRET DROP COLUMN IF EXISTS ID;
ALTER TABLE RSA_SECRET DROP COLUMN IF EXISTS ID;

ALTER TABLE NAMED_SECRET DROP PRIMARY KEY;

ALTER TABLE NAMED_SECRET ADD PRIMARY KEY(UUID);

ALTER TABLE NAMED_SECRET DROP COLUMN IF EXISTS ID;
