-- We don't need to worry about conversions in H2 :)
ALTER TABLE NAMED_CERTIFICATE_AUTHORITY ALTER COLUMN UUID BINARY(16) NOT NULL;

ALTER TABLE NAMED_CERTIFICATE_AUTHORITY DROP PRIMARY KEY;

ALTER TABLE NAMED_CERTIFICATE_AUTHORITY ADD PRIMARY KEY(UUID);

ALTER TABLE NAMED_CERTIFICATE_AUTHORITY DROP COLUMN IF EXISTS ID;
