ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ADD COLUMN TEMP_NOW BIGINT;

UPDATE AUTH_FAILURE_AUDIT_RECORD
  SET TEMP_NOW = CAST(NOW AS BIGINT);

ALTER TABLE AUTH_FAILURE_AUDIT_RECORD DROP COLUMN NOW;

ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ALTER COLUMN TEMP_NOW RENAME TO NOW;
ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ALTER COLUMN NOW SET NOT NULL;
