ALTER TABLE OPERATION_AUDIT_RECORD ADD SCOPE VARCHAR(255);
ALTER TABLE OPERATION_AUDIT_RECORD ADD GRANT_TYPE VARCHAR(255);
ALTER TABLE OPERATION_AUDIT_RECORD ADD CLIENT_ID VARCHAR(255);

ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ADD SCOPE VARCHAR(255);
ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ADD GRANT_TYPE VARCHAR(255);
ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ADD CLIENT_ID VARCHAR(255);
