BEGIN TRANSACTION;

ALTER TABLE PASSWORD_SECRET
ADD CONSTRAINT PASSWORD_SECRET_UUID_FOREIGN_KEY
FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) ON DELETE CASCADE
NOCHECK;

ALTER TABLE VALUE_SECRET
ADD CONSTRAINT VALUE_SECRET_UUID_FOREIGN_KEY
FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) ON DELETE CASCADE
NOCHECK;

ALTER TABLE CERTIFICATE_SECRET
ADD CONSTRAINT CERTIFICATE_SECRET_UUID_FOREIGN_KEY
FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) ON DELETE CASCADE
NOCHECK;

ALTER TABLE SSH_SECRET
ADD CONSTRAINT SSH_SECRET_UUID_FOREIGN_KEY
FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) ON DELETE CASCADE
NOCHECK;

ALTER TABLE RSA_SECRET
ADD CONSTRAINT RSA_SECRET_UUID_FOREIGN_KEY
FOREIGN KEY(UUID) REFERENCES NAMED_SECRET(UUID) ON DELETE CASCADE
NOCHECK;

COMMIT;
