ALTER TABLE OPERATION_AUDIT_RECORD ADD METHOD VARCHAR(255);
ALTER TABLE OPERATION_AUDIT_RECORD ADD STATUS_CODE INT;

ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ADD METHOD VARCHAR(255);
ALTER TABLE AUTH_FAILURE_AUDIT_RECORD ADD STATUS_CODE INT;
