CREATE SEQUENCE SYSTEM_SEQUENCE_NAMED_CANARY START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE NAMED_CANARY(
    ID BIGINT DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_NAMED_CANARY) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_NAMED_CANARY,
    ENCRYPTED_VALUE BINARY(7016),
    NAME VARCHAR(255) NOT NULL,
    NONCE BINARY(16)
);