CREATE CACHED TABLE SSH_SECRET(
    PUBLIC_KEY VARCHAR(7000),
    ID BIGINT NOT NULL
);
ALTER TABLE SSH_SECRET ADD CONSTRAINT CONSTRAINT_42 PRIMARY KEY(ID);
ALTER TABLE SSH_SECRET ADD CONSTRAINT SSH_SECRET_FKEY FOREIGN KEY(ID) REFERENCES NAMED_SECRET(ID) NOCHECK;