:sectnums:
:sectnumlevels: 2
:toc: left
:toclevels: 2
:toc-title: CredHub API
:page-layout: docs

= CredHub API

== Permissions

=== Get a Permission by Actor and Path
operation::GET__permissions_by_actor_and_path__returns_a_permission[]

---

=== Get a Permission by UUID
operation::GET__permissions_by_uuid__returns_a_permission[]

---

=== Create a Permission
operation::POST__permissions__returns_a_permission[]

---

=== Update a Permission
operation::PUT__permissions__returns_a_permission[]

---

=== Update a Permission Operation
operation::PATCH__permissions__returns_a_permission[]

---

=== Delete a Permission
operation::DELETE__permissions_by_uuid__returns_a_permission[]

== Credentials

=== Find a Credential by Path
operation::GET__find_by_path_returns__results[]

---

=== Generate a Certificate Credential
operation::POST__generate_certificate_returns__certificate_credential[]

---

=== Generate a Password Credential
operation::POST__generate_password_returns__password_credential[]

---

=== Generate a User Credential
operation::POST__generate_user_returns__user_credential[]

---

=== Generate a RSA Credential
operation::POST__generate_rsa_returns__rsa_credential[]

---

=== Generate a SSH Credential
operation::POST__generate_ssh_returns__ssh_credential[]

---

=== Set a Value Credential
operation::PUT__set_value_credential_returns__value_credential[]
