:sectnums:
:sectnumlevels: 2
:toc: left
:toclevels: 2
:toc-title: CredHub API
:page-layout: docs

= CredHub API

== Permissions

=== Get a Permission by Actor and Path
operation::GET__permissions_by_actor_and_path__returns_a_permission[]

---

=== Get a Permission by UUID
operation::GET__permissions_by_uuid__returns_a_permission[]

---

=== Create a Permission
operation::POST__permissions__returns_a_permission[]

---

=== Update a Permission
operation::PUT__permissions__returns_a_permission[]

---

=== Update a Permission Operation
operation::PATCH__permissions__returns_a_permission[]

---

=== Delete a Permission
operation::DELETE__permissions_by_uuid__returns_a_permission[]

== Credentials

=== Find a Credential by Name
operation::GET__find_by_name__returns_results[]

---

=== Find a Credential by ID (Type: Value)
operation::GET__find_by_id__returns_value_results[]

---

=== Find a Credential by ID (Type: JSON)
operation::GET__find_by_id__returns_json_results[]

---

=== Find a Credential by ID (Type: Password)
operation::GET__find_by_id__returns_password_results[]

---

=== Find a Credential by ID (Type: User)
operation::GET__find_by_id__returns_user_results[]

---

=== Find a Credential by ID (Type: Certificate)
operation::GET__find_by_id__returns_certificate_results[]

---

=== Find a Credential by ID (Type: RSA)
operation::GET__find_by_id__returns_rsa_results[]

---

=== Find a Credential by ID (Type: SSH)
operation::GET__find_by_id__returns_ssh_results[]

---

=== Find a Credential by Name-Like
operation::GET__find_by_name_like__returns_results[]

---

=== Get a Credential by Name
operation::GET__get_by_name__returns_results[]

---

=== Generate a Certificate Credential
operation::POST__generate_certificate_returns__certificate_credential[]

---

=== Generate a Password Credential
operation::POST__generate_password_returns__password_credential[]

---

=== Generate a User Credential
operation::POST__generate_user_returns__user_credential[]

---

=== Generate a RSA Credential
operation::POST__generate_rsa_returns__rsa_credential[]

---

=== Generate a SSH Credential
operation::POST__generate_ssh_returns__ssh_credential[]

---

=== Set a JSON Credential
operation::PUT__set_json_credential_returns__json_credential[]

---

=== Set a Certificate Credential
operation::PUT__set_certificate_credential_returns__certificate_credential[]

---

=== Set a Password Credential
operation::PUT__set_password_credential_returns__password_credential[]

---

=== Set a RSA Credential
operation::PUT__set_rsa_credential_returns__rsa_credential[]

---

=== Set a SSH Credential
operation::PUT__set_ssh_credential_returns__ssh_credential[]

---

=== Set a User Credential
operation::PUT__set_user_credential_returns__user_credential[]

---

=== Set a Value Credential
operation::PUT__set_value_credential_returns__value_credential[]

---

=== Delete a Credential
operation::DELETE__credential_returns__void[]

---

== Interpolation

=== Interpolate a JSON Object
operation::POST__interpolate__returns_map[]

---

== Management

=== Get Read Only Mode Status
operation::GET__management_mode__returns_result[]

---

=== Set Read Only Mode Status
operation::POST__management_mode__returns_result[]

---

== Encryption Key Usage

=== Get Encryption Key Usage

---