spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    group:
      "dev": "dev-remote-uaa"

management:
  endpoints:
    web:
      base-path: /
    access:
      default: none
  endpoint:
    health:
      access: unrestricted
  server:
    ssl:
      enabled: false
    port: 9001
