name: unit-test-java11

on:
  push:
    branches:
      - '**java11'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '11'
      - name: Build and test with Gradle
        run: ./gradlew clean build
