
== Certificates Endpoint

=== Rotation Instructions

See https://github.com/pivotal-cf/credhub-release/blob/master/docs/ca-rotation.md[here] for certificate rotation instructions.

---

=== Get All Certificates
operation::GET__certificates__returns_certificates[]

Note: The certificate versions will be sorted in descending order of their creation date.

---

=== Get a Certificate By Name
operation::GET__certificates_byName__returns_certificate[]

Note: The certificate versions will be sorted in descending order of their creation date.

---

=== Regenerate a Certificate
operation::POST__certificates_uuid_regenerate__returns_certificate[]

Note:

* If a certificate credential only has one version and it is marked as transitional the credential cannot be regenerated using this endpoint.
* If the duration used to generate the currently active version of the certificate is lower than the minimum duration, the regenerated certificate will use the minimum duration instead and the response will contain the duration_overridden flag set to true.

---

=== Update Transitional Version
operation::PUT__updateTransitionalVersion__returns_certificate[]

---

=== Get All Versions of a Certificate
operation::GET__certificateVersions__returns_certificates[]

Note: The certificate versions will be sorted in descending order of their creation date.

---

=== Create a Version of a Certificate
operation::POST__certificateVersions__returns_certificate[]

---

=== Delete a Version of a Certificate
operation::DELETE__certificateVersion__returns_certificate[]
