
== Certificates Endpoint

=== Rotation Instructions

See https://github.com/pivotal-cf/credhub-release/blob/master/docs/ca-rotation.md[here] for certificate rotation instructions.

---

=== Minimum Duration

A minimum duration can be configured for leaf and CA certificates using the `certificates.leaf_minimum_duration_in_days` and `certificates.ca_minimum_duration_in_days` server-level configuration fields. When these fields are configured, if a request to generate or regenerate a certificate has a duration lower than the minimum, then the minimum duration is used instead.

The API response will include two fields:

* A `duration_overridden` field that is `true` when the minimum duration was used instead, or `false` if the requested duration was used.
* A `duration_used` field that is the duration (in days) used when the certificate was generated.

---

=== Get All Certificates
operation::GET__certificates__returns_certificates[]

Note: The certificate versions will be sorted in descending order of their creation date.

---

=== Get a Certificate By Name
operation::GET__certificates_byName__returns_certificate[]

Note: The certificate versions will be sorted in descending order of their creation date.

---

=== Regenerate a Certificate
operation::POST__certificates_uuid_regenerate__returns_certificate[]

Note:

* If a certificate credential only has one version and it is marked as transitional the credential cannot be regenerated using this endpoint.
* If the duration used to generate the currently active version of the certificate is lower than the minimum duration, the regenerated certificate will use the minimum duration instead and the response will contain the `duration_overridden` flag set to true. The duration value used to regenerate the certificate is included in the `duration_used` field of the response.

---

=== Update Transitional Version
operation::PUT__updateTransitionalVersion__returns_certificate[]

---

=== Get All Versions of a Certificate
operation::GET__certificateVersions__returns_certificates[]

Note: The certificate versions will be sorted in descending order of their creation date.

---

=== Create a Version of a Certificate
operation::POST__certificateVersions__returns_certificate[]

---

=== Delete a Version of a Certificate
operation::DELETE__certificateVersion__returns_certificate[]
