
== Credentials Endpoint

=== Overview

Credentials are the primary object in CredHub.
Any passwords, secrets, configurations or other sensitive information that you store is saved to a named credential.
You can retrieve, update and delete a credential using its name.

All credentials, regardless of type, share a common namespace, e.g. a credential named `/diego-tls` exists once in CredHub.
Credential names are not reservable, so two users updating a credential of the same name will result in updates to the same credential.
If you prefer a separate namespace for your credentials, you can add a path prior to the credential name.

Credentials are typed based on the format of the stored value, value validation and generation procedure.
Once a credential type has been set, it cannot be updated to a new type.
If you mistakenly set the type, you must delete the credential, then set it with the correct type.

When viewing all versions of a credential, the versions will be returned in descending order of their creation date.

---

=== Find a Credential by Path
operation::GET__find_by_path__returns_results[]

Note: If a certificate credential only has one version and it is marked as transitional the credential name will not be returned by this endpoint.

---

=== Find a Credential by ID (Type: Value)
operation::GET__find_by_id__returns_value_results[]

---

=== Find a Credential by ID (Type: JSON)
operation::GET__find_by_id__returns_json_results[]

---

=== Find a Credential by ID (Type: Password)
operation::GET__find_by_id__returns_password_results[]

---

=== Find a Credential by ID (Type: User)
operation::GET__find_by_id__returns_user_results[]

---

=== Find a Credential by ID (Type: Certificate)
operation::GET__find_by_id__returns_certificate_results[]

---

=== Find a Credential by ID (Type: RSA)
operation::GET__find_by_id__returns_rsa_results[]

---

=== Find a Credential by ID (Type: SSH)
operation::GET__find_by_id__returns_ssh_results[]

---

=== Find a Credential by Name-Like
operation::GET__find_by_name_like__returns_results[]

---

=== Get a Credential by Name
operation::GET__get_by_name__returns_results[]

---

=== Generate a Certificate Credential
operation::POST__generate_certificate_returns__certificate_credential[]

---

=== Generate a Password Credential
operation::POST__generate_password_returns__password_credential[]

---

=== Generate a User Credential
operation::POST__generate_user_returns__user_credential[]

---

=== Generate a RSA Credential
operation::POST__generate_rsa_returns__rsa_credential[]

---

=== Generate a SSH Credential
operation::POST__generate_ssh_returns__ssh_credential[]

---

=== Set a JSON Credential
operation::PUT__set_json_credential_returns__json_credential[]

---

=== Set a Certificate Credential
operation::PUT__set_certificate_credential_returns__certificate_credential[]

---

=== Set a Password Credential
operation::PUT__set_password_credential_returns__password_credential[]

---

=== Set a RSA Credential
operation::PUT__set_rsa_credential_returns__rsa_credential[]

---

=== Set a SSH Credential
operation::PUT__set_ssh_credential_returns__ssh_credential[]

---

=== Set a User Credential
operation::PUT__set_user_credential_returns__user_credential[]

---

=== Set a Value Credential
operation::PUT__set_value_credential_returns__value_credential[]

---

=== Delete a Credential
operation::DELETE__credential_returns__void[]
