
== Credentials Endpoint

=== Overview

Credentials are the primary object in CredHub.
Any passwords, secrets, configurations or other sensitive information that you store is saved to a named credential.
You can retrieve, update and delete a credential using its name. Each credential has a maximum size of 64 KB.

All credentials, regardless of type, share a common namespace, e.g. a credential named `/diego-tls` exists once in CredHub.
Credential names are not reservable, so two users updating a credential of the same name will result in updates to the same credential.
If you prefer a separate namespace for your credentials, you can add a path prior to the credential name.

Credentials are typed based on the format of the stored value, value validation and generation procedure.
Once a credential type has been set, it cannot be updated to a new type.
If you mistakenly set the type, you must delete the credential, then set it with the correct type.

When viewing all versions of a credential, the versions will be returned in descending order of their creation date.

---

=== Find a Credential by Path
Returns an array of versions, sorted in order from newest to oldest.

operation::getFind_by_path__returns_results[]

Note: If a certificate credential only has one version and it is marked as transitional the credential name will not be returned by this endpoint.

---

=== Find a Credential by ID (Type: Value)
operation::getFind_by_id__returns_value_results[]

---

=== Find a Credential by ID (Type: JSON)
operation::getFind_by_id__returns_json_results[]

---

=== Find a Credential by ID (Type: Password)
operation::getFind_by_id__returns_password_results[]

---

=== Find a Credential by ID (Type: User)
operation::getFind_by_id__returns_user_results[]

---

=== Find a Credential by ID (Type: Certificate)
operation::getFind_by_id__returns_certificate_results[]

---

=== Find a Credential by ID (Type: RSA)
operation::getFind_by_id__returns_rsa_results[]

---

=== Find a Credential by ID (Type: SSH)
operation::getFind_by_id__returns_ssh_results[]

---

=== Find a Credential by Name-Like
Returns an array of versions, sorted in order from newest to oldest.

operation::getFind_by_name_like__returns_results[]

---

=== Get a Credential by Name
operation::getGet_by_name__returns_results[]

---

=== Generate a Certificate Credential
operation::postGenerateCertificateReturnsCertificateCredential[]

Notes: 

* If the duration is overridden by the minimum duration, the response will contain the `duration_overridden` flag set to true. It will also include the actual duration used to generate the certificate in the `duration_used` field.
* When the mode is set to converge, certificates are no longer regenerated if the duration doesn't match the existing certificate's duration.

---

=== Generate a Password Credential
operation::postGeneratePasswordReturnsPasswordCredential[]

---

=== Generate a User Credential
operation::postGenerateUserReturnsUserCredential[]

---

=== Generate a RSA Credential
operation::postGenerateRsaReturnsRsaCredential[]

---

=== Generate a SSH Credential
operation::postGenerateSshReturnsSshCredential[]

---

=== Set a JSON Credential
operation::putSetJsonCredentialReturnsJsonCredential[]

---

=== Set a Certificate Credential
operation::putSet_certificate_credential_returns__certificate_credential[]

---

=== Set a Password Credential
operation::putSetPasswordCredentialReturnsPasswordCredential[]

---

=== Set a RSA Credential
operation::putSet_rsa_credential_returns__rsa_credential[]

---

=== Set a SSH Credential
operation::putSet_ssh_credential_returns__ssh_credential[]

---

=== Set a User Credential
operation::putSet_user_credential_returns__user_credential[]

---

=== Set a Value Credential
operation::putSet_user_credential_returns__user_credential[]

---

=== Delete a Credential
operation::deleteCredential_returns__void[]
